// Database to display the product using the product Id(proid)
const ForBuyers = [
    {proid : 100, imageUrl : "./images/buyhouse1.jfif", title : " 3 BHK Flat for sale in padi", buy : "Buy : 12 lakhs", buildUp : "BuildUp : 2,567sq.ft", EMI : "EMI : 8,775/Month", dataItem : "padi"},
    {proid : 101, imageUrl : "./images/buyhouse2.jfif", title : " 1 BHK Flat for sale in Guindy", buy : "Buy : 9 lakhs", buildUp : "BuildUp : 967sq.ft", EMI : "EMI : 4,543/Month", dataItem : "guindy"},
    {proid : 102, imageUrl : "./images/buyhouse3.jfif", title : " 4 BHK Flat for sale in Anna nagar", buy : "Buy : 25 lakhs", buildUp : "BuildUp : 3,567sq.ft", EMI : "EMI : 10,795/Month", dataItem : "anna nagar"},
    {proid : 103, imageUrl : "./images/buyhouse4.jfif", title : " 2 BHK Flat for sale in Mambalam", buy : "Buy : 17 lakhs", buildUp : "BuildUp : 2,598sq.ft", EMI : "EMI : 8,676/Month", dataItem : "mambalam"},
    {proid : 104, imageUrl : "./images/buyhouse5.jfif", title : " 1 RK Flat for sale in periyamet", buy : "Buy : 8 lakhs", buildUp : "BuildUp : 688sq.ft", EMI : "EMI : 3,775/Month", dataItem : "periyamet"},
    {proid : 105, imageUrl : "./images/buyhouse 6.jfif", title :" 2 BHK Flat for sale in Egmore", buy : "Buy : 23 lakhs", buildUp : "BuildUp : 1,232sq.ft", EMI : "EMI : 11,855/Month", dataItem : "egmore"},
    {proid : 106, imageUrl : "./images/buyhouse1.jfif", title : " 3 BHK Flat for sale in Nanganalur", buy : "Buy : 25 lakhs", buildUp : "BuildUp : 2,123sq.ft", EMI : "EMI : 12,704/Month", dataItem : "nanganalur"},
    {proid : 107, imageUrl : "./images/buyhouse2.jfif", title : " 4 BHK Flat for sale in Alandur", buy : "Buy : 30 lakhs", buildUp : "BuildUp : 3,432sq.ft", EMI : "EMI : 15,644/Month", dataItem : "alandur"},
    {proid : 108, imageUrl : "./images/buyhouse3.jfif", title : " 2 BHK Flat for sale in Pallavaram", buy : "Buy : 10 lakhs", buildUp : "BuildUp : 1,656sq.ft", EMI : "EMI : 8,756/Month", dataItem : "pallavaram"},
    {proid : 109, imageUrl : "./images/buyhouse5.jfif", title : " 2 BHK Flat for sale in Tambaram  ", buy : "Buy : 18 lakhs", buildUp : "BuildUp : 1,765sq.ft", EMI : "EMI : 9,743/Month", dataItem : "tambaram"},
    {proid : 110, imageUrl : "./images/buyhouse4.jfif", title : " 4 BHK Flat for sale in Camp Road  ", buy : "Buy : 28 lakhs", buildUp : "BuildUp : 3,798sq.ft", EMI : "EMI : 15,578/Month", dataItem : "camp road"},
    {proid : 111, imageUrl : "./images/buyhouse 6.jfif", title : " 3 BHK Flat for sale in Chrompet  ", buy : "Buy : 20 lakhs", buildUp : "BuildUp : 1,465sq.ft", EMI : "EMI : 11,164/Month", dataItem : "chrompet"}
];
const BuyersProfile = [
    {proid : 100, imageUrl : "./images/buyhouse1.jfif", imageUrl2: "./images/Buy.jfif", imageUrl3:"./images/Buy1.jfif", title : " 3 BHK Flat for sale in padi", buy : "Buy : 12 lakhs", buildUp : "BuildUp : 2,567sq.ft", EMI : "EMI : 8,775/Month", bedRooms : "3 BedRoom", propertyType : "Flat", apartment : "MS builders", possession : "July 23,2025", parking : "Bike", powerBackup : "Full", balcony : "2", postedOn : "Jun 21,2023", address : "Next to kavery hospital, 200 Feet Radial Road,Padi", descriptionBuy : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 101, imageUrl : "./images/buyhouse2.jfif", imageUrl2: "./images/Buy.jfif", imageUrl3:"./images/Buy1.jfif", title : " 1 BHK House for sale in Guindy", buy : "Buy : 9 lakhs", buildUp : "BuildUp : 967sq.ft", EMI : "EMI : 4,543/Month", bedRooms : "1 BedRoom", propertyType : "Independent House", apartment : "MS builders", possession : "Oct 01,2024", parking : "Bike", powerBackup : "Full", balcony : "0", postedOn : "Jan 11,2023", address : "Near LIC Building, Mount Road,Guindy", descriptionBuy : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 102, imageUrl : "./images/buyhouse3.jfif", imageUrl2: "./images/Buy.jfif", imageUrl3:"./images/Buy1.jfif", title : " 4 BHK Flat for sale in Anna nagar", buy : "Buy : 25 lakhs", buildUp : "BuildUp : 3,567sq.ft", EMI : "EMI : 10,795/Month", bedRooms : "4 BedRoom", propertyType : "Flat", apartment : "MS builders", possession : "Mar 03,2026", parking : "Bike", powerBackup : "Full", balcony : "2", postedOn : "Jun 30,2023", address : "Near to Appolo hospital, 100 Feet Road,Anna Nagar", descriptionBuy : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 103, imageUrl : "./images/buyhouse4.jfif", imageUrl2: "./images/Buy.jfif", imageUrl3:"./images/Buy1.jfif", title : " 2 BHK Flat for sale in Mambalam", buy : "Buy : 17 lakhs", buildUp : "BuildUp : 2,598sq.ft", EMI : "EMI : 8,676/Month", bedRooms : "2 BedRoom", propertyType : "Flat", apartment : "MS buildersor", possession : "Apr 09,2025", parking : "Bike", powerBackup : "Full", balcony : "3", postedOn : "Mar 10,2023", address : "Near KS academy, ,Mambalam", descriptionBuy : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 104, imageUrl : "./images/buyhouse5.jfif", imageUrl2: "./images/Buy.jfif", imageUrl3:"./images/Buy1.jfif", title : " 1 RK House for sale in periyamet", buy : "Buy : 8 lakhs", buildUp : "BuildUp : 688sq.ft", EMI : "EMI : 3,775/Month", bedRooms : "1 BedRoom", propertyType : "Independent House", apartment : "MS builders", possession : "Aug 17,2023", parking : "Bike", powerBackup : "Full", balcony : "1", postedOn : "Apr 03,2023", address : "Next to park station,Periyamet", descriptionBuy : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 105, imageUrl : "./images/buyhouse 6.jfif", imageUrl2: "./images/Buy.jfif", imageUrl3:"./images/Buy1.jfif", title :" 2 BHK Flat for sale in Egmore", buy : "Buy : 23 lakhs", buildUp : "BuildUp : 1,232sq.ft", EMI : "EMI : 11,855/Month", bedRooms : "2 BedRoom", propertyType : "Flat", apartment : "MS builders", possession : "Dec 31,2025", parking : "Bike", powerBackup : "Full", balcony : "4", postedOn : "Feb 28,2023", address : "Next to High Court,Egmore", descriptionBuy : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 106, imageUrl : "./images/buyhouse1.jfif", imageUrl2: "./images/Buy.jfif", imageUrl3:"./images/Buy1.jfif", title : " 3 BHK Flat for sale in Nanganalur", buy : "Buy : 25 lakhs", buildUp : "BuildUp : 2,123sq.ft", EMI : "EMI : 12,704/Month", bedRooms : "3 BedRoom", propertyType : "Flat", apartment : "MS builders", possession : "Jan 15,2025", parking : "Bike", powerBackup : "Full", balcony : "2", postedOn : "July 08,2023", address : "Next to Baroda Bank, Gandhi Road,Nangalur", descriptionBuy : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 107, imageUrl : "./images/buyhouse2.jfif", imageUrl2: "./images/Buy.jfif", imageUrl3:"./images/Buy1.jfif", title : " 4 BHK Flat for sale in Alandur", buy : "Buy : 30 lakhs", buildUp : "BuildUp : 3,432sq.ft", EMI : "EMI : 15,644/Month", bedRooms : "4 BedRoom", propertyType : "Flat", apartment : "MS buildersor", possession : "Feb 27,2027", parking : "Bike", powerBackup : "Full", balcony : "0", postedOn : "Feb 14,2023", address : "Near Metro Station,Alandur", descriptionBuy : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 108, imageUrl : "./images/buyhouse3.jfif", imageUrl2: "./images/Buy.jfif", imageUrl3:"./images/Buy1.jfif", title : " 2 BHK House for sale in Pallavaram", buy : "Buy : 10 lakhs", buildUp : "BuildUp : 1,656sq.ft", EMI : "EMI : 8,756/Month", bedRooms : "2 BedRoom", propertyType : "Independent House", apartment : "MS builders", possession : "Sep 28,2025", parking : "Bike", powerBackup : "Full", balcony : "2", postedOn : "Jan 25,2023", address : "Next to Olympiya Flat,Pallavaram", descriptionBuy : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 109, imageUrl : "./images/buyhouse5.jfif", imageUrl2: "./images/Buy.jfif", imageUrl3:"./images/Buy1.jfif", title : " 2 BHK House for sale in Tambaram  ", buy : "Buy : 18 lakhs", buildUp : "BuildUp : 1,765sq.ft", EMI : "EMI : 9,743/Month", bedRooms : "2 BedRoom", propertyType : "Independent House", apartment : "MS builders", possession : "July 02,2025", parking : "Bike", powerBackup : "Full", balcony : "1", postedOn : "Jun 10,2023", address : "Near to Amaravathy hospital,Tambaram", descriptionBuy : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 110, imageUrl : "./images/buyhouse4.jfif", imageUrl2: "./images/Buy.jfif", imageUrl3:"./images/Buy1.jfif", title : " 4 BHK Flat for sale in Camp Road  ", buy : "Buy : 28 lakhs", buildUp : "BuildUp : 3,798sq.ft", EMI : "EMI : 15,578/Month", bedRooms : "4 BedRoom", propertyType : "Flat", apartment : "MS buildersor", possession : "Jun 11,2025", parking : "Bike", powerBackup : "Full", balcony : "3", postedOn : "Mar 21,2023", address : "Near to KFC, 100 Feet Road,Camp Road", descriptionBuy : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 111, imageUrl : "./images/buyhouse 6.jfif", imageUrl2: "./images/Buy.jfif", imageUrl3:"./images/Buy1.jfif", title : " 3 BHK Flat for sale in Chrompet  ", buy : "Buy : 20 lakhs", buildUp : "BuildUp : 1,465sq.ft", EMI : "EMI : 11,164/Month", bedRooms : "3 BedRoom", propertyType : "Flat", apartment : "MS builders", possession : "Oct 15,2023", parking : "Bike", powerBackup : "Full", balcony : "4", postedOn : "Apr 01,2023", address : "Next to Parvathy hospital,Chrompet", descriptionBuy : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."}
];



// For Rent

const ForRental = [
    {proid : 112, imageUrl: "./images/Rent house 0.jfif", title : " 2 BHK House for Rent in Tirusulam", rent : "Rent : 6,000", buildUp : "BuildUp : 876sq.ft", deposit : "Deposit : RS.25,000",dataItem : "Tirusulam"},
    {proid : 113, imageUrl: "./images/Rent house1.jfif",  title : " 3 BHK House for Rent in Velacherry", rent : "Rent : 17,700", buildUp : "BuildUp : 1076sq.ft", deposit : "Deposit : RS.60,000",dataItem : "Velacherry"},
    {proid : 114, imageUrl: "./images/Rent house 2.jfif", title : " 1 RK House for Rent in Amjikarai", rent : "Rent : 5,500", buildUp : "BuildUp : 568sq.ft", deposit : "Deposit : RS.30,000",dataItem : "Amjikarai"},
    {proid : 115, imageUrl: "./images/Rent house 3.jfif", title : " 4 BHK House for Rent in The Park", rent : "Rent : 16,500", buildUp : "BuildUp : 3,463sq.ft", deposit : "Deposit : RS.35,000",dataItem : "The Park"},
    {proid : 116, imageUrl: "./images/Rent house 4.jfif", title : " 3 BHK House for Rent in Navalur", rent : "Rent : 10,200", buildUp : "BuildUp : 1,847sq.ft", deposit : "Deposit : RS.40,000",dataItem : "Navalur"},
    {proid : 117, imageUrl: "./images/Rent house 5.jfif", title : " 2 BHK House for Rent in Pallavaram", rent : "Rent : 8,500", buildUp : "BuildUp : 984sq.ft", deposit : "Deposit : RS.25,000",dataItem : "Pallavaram"},
    {proid : 118, imageUrl: "./images/Rent house 6.jfif", title : " 1 BHK House for Rent in Sanatorium", rent : "Rent : 8,500", buildUp : "BuildUp : 543sq.ft", deposit : "Deposit : RS.20,000",dataItem : "Sanatorium"},
    {proid : 119, imageUrl: "./images/Rent house 2.jfif", title : " 2 BHK House for Rent in Keelkatalai", rent : "Rent : 7,000", buildUp : "BuildUp : 1,221sq.ft", deposit : "Deposit : RS.30,000",dataItem : "Keelkatalai"},
    {proid : 120, imageUrl: "./images/Rent house 3.jfif", title : " 4 BHK House for Rent in Guindy", rent : "Rent : 20,000", buildUp : "BuildUp : 2,930sq.ft", deposit : "Deposit : RS.50,000",dataItem : "Guindy"},
    {proid : 121, imageUrl: "./images/Rent house 4.jfif", title : " 1 BHK House for Rent in Koyambedu", rent : "Rent : 8,000", buildUp : "BuildUp : 665sq.ft", deposit : "Deposit : RS.35,000",dataItem : "Koyambedu"},
    {proid : 122, imageUrl: "./images/Rent house 5.jfif", title : " 3 BHK House for Rent in Vadapalani", rent : "Rent : 12,000", buildUp : "BuildUp : 1,029sq.ft", deposit : "Deposit : RS.45,000",dataItem : "Vadapalani"},
    {proid : 123, imageUrl: "./images/Rent house 6.jfif", title : " 2 BHK House for Rent in IceHouse", rent : "Rent : 10,000", buildUp : "BuildUp : 822sq.ft", deposit : "Deposit : RS.50,000",dataItem : "IceHouse"}
];
const RentalProfile = [
    {proid : 112, imageUrl: "./images/Rent house 0.jfif", imageUrl4: "./images/Rent house 0.jfif", imageUrl5 : "./images/Rent house 4.jfif", title : " 2 BHK House for Rent in Tirusulam", rent : "Rent : 6,000", buildUp : "BuildUp : 876sq.ft", deposit : "Deposit : RS.25,000", bedRooms : "2 BedRoom", propertyType : "House", preferredTenant : "Family", possession : "July 23,2019", parking : "Bike", ageOfBuilding : "4 Years", balcony : "1", postedOn : "Jun 28, 2023", address : "Near Railway station, 200 Feet Road, Tirusulam", descriptionRent : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 113, imageUrl: "./images/Rent house1.jfif", imageUrl4: "./images/Rent house 0.jfif", imageUrl5 : "./images/Rent house 4.jfif", title : " 3 BHK House for Rent in Velacherry", rent : "Rent : 17,700", buildUp : "BuildUp : 1076sq.ft", deposit : "Deposit : RS.60,000", bedRooms : "3 BedRoom", propertyType : "House", preferredTenant : "Family", possession : "Jan 02,2017", parking : "Bike", ageOfBuilding : "5 Years", balcony : "2", postedOn : "Jun 22, 2023",address : "Near Pheonix Market city, 100 Feet Road, Velacherry", descriptionRent : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 114, imageUrl: "./images/Rent house 2.jfif",imageUrl4: "./images/Rent house 0.jfif", imageUrl5 : "./images/Rent house 4.jfif", title : " 1 RK House for Rent in Amjikarai", rent : "Rent : 5,500", buildUp : "BuildUp : 568sq.ft", deposit : "Deposit : RS.30,000", bedRooms : "1 BedRoom", propertyType : "House", preferredTenant : "Family", possession : "Jun 12,2018", parking : "Car", ageOfBuilding : "4 Years", balcony : "3", postedOn : "Jun 20, 2023",address : "Near Passport seva kendra, Amjikarai", descriptionRent : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 115, imageUrl: "./images/Rent house 3.jfif",imageUrl4: "./images/Rent house 0.jfif", imageUrl5 : "./images/Rent house 4.jfif", title : " 4 BHK House for Rent in The Park", rent : "Rent : 16,500", buildUp : "BuildUp : 3,463sq.ft", deposit : "Deposit : RS.35,000", bedRooms : "4 BedRoom", propertyType : "House", preferredTenant : "Family", possession : "Mar 13,2020", parking : "Bike", ageOfBuilding : "2 Years", balcony : "1", postedOn : "May 31, 2023",address : "Near Ribbon Building, Main Road, The Park", descriptionRent : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 116, imageUrl: "./images/Rent house 4.jfif",imageUrl4: "./images/Rent house 0.jfif", imageUrl5 : "./images/Rent house 4.jfif", title : " 3 BHK House for Rent in Navalur", rent : "Rent : 10,200", buildUp : "BuildUp : 1,847sq.ft", deposit : "Deposit : RS.40,000", bedRooms : "3 BedRoom", propertyType : "House", preferredTenant : "Family", possession : "May 30,2022", parking : "Bike", ageOfBuilding : "1 Years", balcony : "1", postedOn : "May 21, 2023",address : "Near Marina Mall, 100 Feet Road, Navalur", descriptionRent : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 117, imageUrl: "./images/Rent house 5.jfif",imageUrl4: "./images/Rent house 0.jfif", imageUrl5 : "./images/Rent house 4.jfif", title : " 2 BHK House for Rent in Pallavaram", rent : "Rent : 8,500", buildUp : "BuildUp : 984sq.ft", deposit : "Deposit : RS.25,000", bedRooms : "2 BedRoom", propertyType : "House", preferredTenant : "Bachelor", possession : "Oct 14,2019", parking : "Car", ageOfBuilding : "4 Years", balcony : "2", postedOn : "Jun 21, 2023",address : "Near Yaa Mohideen, GST Road, Pallavaram", descriptionRent : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 118, imageUrl: "./images/Rent house 6.jfif",imageUrl4: "./images/Rent house 0.jfif", imageUrl5 : "./images/Rent house 4.jfif", title : " 1 BHK House for Rent in Sanatorium", rent : "Rent : 8,500", buildUp : "BuildUp : 543sq.ft", deposit : "Deposit : RS.20,000", bedRooms : "1 BedRoom", propertyType : "House", preferredTenant : "Family", possession : "July 10,2017", parking : "Bike", ageOfBuilding : "5 Years", balcony : "3", postedOn : "Jun 13, 2023",address : "Near MEPZ, Sanatorium", descriptionRent : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 119, imageUrl: "./images/Rent house 2.jfif",imageUrl4: "./images/Rent house 0.jfif", imageUrl5 : "./images/Rent house 4.jfif", title : " 2 BHK House for Rent in Keelkatalai", rent : "Rent : 7,000", buildUp : "BuildUp : 1,221sq.ft", deposit : "Deposit : RS.30,000", bedRooms : "2 BedRoom", propertyType : "House", preferredTenant : "Family", possession : "Feb 20,2022", parking : "Bike", ageOfBuilding : "1 Years", balcony : "1", postedOn : "Jun 22, 2023",address : "Near Bus stop, Madipakkam Main Road, Keelkatalai", descriptionRent : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 120, imageUrl: "./images/Rent house 3.jfif",imageUrl4: "./images/Rent house 0.jfif", imageUrl5 : "./images/Rent house 4.jfif", title : " 4 BHK House for Rent in Guindy", rent : "Rent : 20,000", buildUp : "BuildUp : 2,930sq.ft", deposit : "Deposit : RS.50,000", bedRooms : "4 BedRoom", propertyType : "House", preferredTenant : "Family", possession : "Apr 23,2021", parking : "Car", ageOfBuilding : "2 Years", balcony : "2", postedOn : "Jun 20, 2023",address : "Near Railway station, 100 Feet Road, Guindy", descriptionRent : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 121, imageUrl: "./images/Rent house 4.jfif",imageUrl4: "./images/Rent house 0.jfif", imageUrl5 : "./images/Rent house 4.jfif", title : " 1 BHK House for Rent in Koyambedu", rent : "Rent : 8,000", buildUp : "BuildUp : 665sq.ft", deposit : "Deposit : RS.35,000", bedRooms : "1 BedRoom", propertyType : "House", preferredTenant : "Bachelor", possession : "Dce 07,2015", parking : "Bike", ageOfBuilding : "8 Years", balcony : "1", postedOn : "Jun 17, 2023",address : "Near Bus Stand, Koyambedu", descriptionRent : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 122, imageUrl: "./images/Rent house 5.jfif",imageUrl4: "./images/Rent house 0.jfif", imageUrl5 : "./images/Rent house 4.jfif", title : " 3 BHK House for Rent in Vadapalani", rent : "Rent : 12,000", buildUp : "BuildUp : 1,029sq.ft", deposit : "Deposit : RS.45,000", bedRooms : "3 BedRoom", propertyType : "House", preferredTenant : "Family", possession : "Jan 14,2021", parking : "Bike", ageOfBuilding : "3 Years", balcony : "2", postedOn : "Jun 12, 2023",address : "Near Forum Mall, Main Road, Vadapalani", descriptionRent : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 123, imageUrl: "./images/Rent house 6.jfif",imageUrl4: "./images/Rent house 0.jfif", imageUrl5 : "./images/Rent house 4.jfif", title : " 2 BHK House for Rent in IceHouse", rent : "Rent : 10,000", buildUp : "BuildUp : 822sq.ft", deposit : "Deposit : RS.50,000", bedRooms : "2 BedRoom", propertyType : "House", preferredTenant : "Bachelor", possession : "Oct 19,2020", parking : "Bike", ageOfBuilding : "2 Years", balcony : "4", postedOn : "Jun 01, 2023",address : "Near Triplicane Bus stop, 100 Feet Road, IceHouse", descriptionRent : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."}
];

// For commercial

const ForCommercial = [
    {proid : 124, imageUrl : "./images/Commercial Shops 1.jpg", title : "Office space in Pallavaram, chennai for Rent", rent : "Rent : 20,000" , buildUp : "BuildUp : 600sq.ft", deposit : "Deposit : RS.1 Lac",dataItem : "Pallavaram"},
    {proid : 125, imageUrl : "./images/Commercial Shop 14.jpg", title : "Office space in Guindy, chennai for Rent", rent : "Rent : 14,000" , buildUp : "BuildUp : 760sq.ft", deposit : "Deposit : RS.2 Lac",dataItem : "Guindy"},
    {proid : 126, imageUrl : "./images/Commercial Shop 13.jpg", title : "Office space in Anakaputhur, chennai for Rent", rent : "Rent : 15,000" , buildUp : "BuildUp : 478sq.ft", deposit : "Deposit : RS.1.5 Lac",dataItem : "Anakaputhur"},
    {proid : 127, imageUrl : "./images/Commercial Shop 4.jpg", title : "Office space in Kundrathur, chennai for Rent", rent : "Rent : 25,000" , buildUp : "BuildUp : 753sq.ft", deposit : "Deposit : RS.3 Lac",dataItem : "Kundrathur"},
    {proid : 128, imageUrl : "./images/Commercial Shop 5.jpg", title : "Office space in Royapuram, chennai for Rent", rent : "Rent : 60,000" , buildUp : "BuildUp : 655sq.ft", deposit : "Deposit : RS.5 Lac",dataItem : "Royapuram"},
    {proid : 129, imageUrl : "./images/Commercial Shop 6.jpg", title : "Office space in Ennore, chennai for Rent", rent : "Rent : 90,000" , buildUp : "BuildUp : 1,232sq.ft", deposit : "Deposit : RS.6 Lac",dataItem : "Ennore"},
    {proid : 130, imageUrl : "./images/Commercial Shop 7.jpg", title : "Office space in Pudupettai, chennai for Rent", rent : "Rent : 18,000" , buildUp : "BuildUp : 675sq.ft", deposit : "Deposit : RS.2.5 Lac",dataItem : "Pudupettai"},
    {proid : 131, imageUrl : "./images/Commercial Shop 15.jpg", title : "Office space in VyasarPadi, chennai for Rent", rent : "Rent : 12,000" , buildUp : "BuildUp : 603sq.ft", deposit : "Deposit : RS.1.6 Lac",dataItem : "Vyasarpadi"},
    {proid : 132, imageUrl : "./images/Commercial Shop 9.jpg", title : "Office space in Koyambedu, chennai for Rent", rent : "Rent : 28,000" , buildUp : "BuildUp : 843sq.ft", deposit : "Deposit : RS.3.2 Lac",dataItem : "Koyambedu"},
    {proid : 133, imageUrl : "./images/Commercial Shop 10.jpg", title : "Office space in Adyar, chennai for Rent", rent : "Rent : 12,000" , buildUp : "BuildUp : 450sq.ft", deposit : "Deposit : RS.1 Lac",dataItem : "Adyar"},
    {proid : 134, imageUrl : "./images/Commercial Shop 11.jpg", title : "Office space in T.Nagar, chennai for Rent", rent : "Rent : 22,000" , buildUp : "BuildUp : 520sq.ft", deposit : "Deposit : RS.2 Lac",dataItem : "T.Nagar"},
    {proid : 135, imageUrl : "./images/Commercial Shop 12.jpg", title : "Office space in Madipakam, chennai for Rent", rent : "Rent : 45,000" , buildUp : "BuildUp : 789sq.ft", deposit : "Deposit : RS.4 Lac",dataItem : "Madipakam"},
];

const CommercialProfile = [
    {proid : 124, imageUrl : "./images/Commercial Shops 1.jpg", imageUrl6 : "./images/Commercial Shop 14.jpg", imageUrl7 : "./images/Commercial Shop 11.jpg" ,title : "Office space in Pallavaram, chennai for Rent", rent : "Rent : 20,000" , buildUp : "BuildUp : 600sq.ft", deposit : "Deposit : RS.1 Lac", address : "Near st.Sebastian school, GST Road, Pallavaram", descriptionCom : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 125, imageUrl : "./images/Commercial Shop 14.jpg", imageUrl6 : "./images/Commercial Shop 4.jpg", imageUrl7 : "./images/Commercial Shop 7.jpg" , title : "Office space in Guindy, chennai for Rent", rent : "Rent : 14,000" , buildUp : "BuildUp : 760sq.ft", deposit : "Deposit : RS.2 Lac", address : "Near National Park, Main Road, Guindy", descriptionCom : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 126, imageUrl : "./images/Commercial Shop 13.jpg", imageUrl6 : "./images/Commercial Shop 4.jpg", imageUrl7 : "./images/Commercial Shop 13.jpg" , title : "Office space in Anakaputhur, chennai for Rent", rent : "Rent : 15,000" , buildUp : "BuildUp : 478sq.ft", deposit : "Deposit : RS.1.5 Lac", address : "Next Bus Stop, Anna Salai, Anakaputhur", descriptionCom : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 127, imageUrl : "./images/Commercial Shop 4.jpg", imageUrl6 : "./images/Commercial Shop 4.jpg", imageUrl7 : "./images/Commercial Shop 14.jpg" , title : "Office space in Kundrathur, chennai for Rent", rent : "Rent : 25,000" , buildUp : "BuildUp : 753sq.ft", deposit : "Deposit : RS.3 Lac", address : "Near MKV Mahal, Ponnamalle Main Road, Kundrathur", descriptionCom : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 128, imageUrl : "./images/Commercial Shop 5.jpg", imageUrl6 : "./images/Commercial Shop 3.jpg", imageUrl7 : "./images/Commercial Shop 15.jpg" , title : "Office space in Royapuram, chennai for Rent", rent : "Rent : 60,000" , buildUp : "BuildUp : 655sq.ft", deposit : "Deposit : RS.5 Lac", address : "Near Market, 100 Feet Road, Royapuram", descriptionCom : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 129, imageUrl : "./images/Commercial Shop 6.jpg", imageUrl6 : "./images/Commercial Shop 5.jpg", imageUrl7 : "./images/Commercial Shops 1.jpg" , title : "Office space in Ennore, chennai for Rent", rent : "Rent : 90,000" , buildUp : "BuildUp : 1,232sq.ft", deposit : "Deposit : RS.6 Lac", address : "Next Ennore Harbour, Main Road, Ennore", descriptionCom : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 130, imageUrl : "./images/Commercial Shop 7.jpg", imageUrl6 : "./images/Commercial Shop 6.jpg", imageUrl7 : "./images/Commercial Shop 3.jpg" , title : "Office space in Pudupettai, chennai for Rent", rent : "Rent : 18,000" , buildUp : "BuildUp : 675sq.ft", deposit : "Deposit : RS.2.5 Lac", address : "Near Bus stand, Pudupettai", descriptionCom : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 131, imageUrl : "./images/Commercial Shop 15.jpg", imageUrl6 : "./images/Commercial Shop 7.jpg", imageUrl7 : "./images/Commercial Shop 4.jpg" , title : "Office space in VyasarPadi, chennai for Rent", rent : "Rent : 12,000" , buildUp : "BuildUp : 603sq.ft", deposit : "Deposit : RS.1.6 Lac", address : "Near RailWay Station, VyasarPadi", descriptionCom : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 132, imageUrl : "./images/Commercial Shop 9.jpg", imageUrl6 : "./images/Commercial Shop 12.jpg", imageUrl7 : "./images/Commercial Shop 5.jpg" , title : "Office space in Koyambedu, chennai for Rent", rent : "Rent : 28,000" , buildUp : "BuildUp : 843sq.ft", deposit : "Deposit : RS.3.2 Lac", address : "Near Koyambedu Market, Koyambedu", descriptionCom : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 133, imageUrl : "./images/Commercial Shop 10.jpg", imageUrl6 : "./images/Commercial Shop 11.jpg", imageUrl7 : "./images/Commercial Shop 6.jpg" , title : "Office space in Adyar, chennai for Rent", rent : "Rent : 12,000" , buildUp : "BuildUp : 450sq.ft", deposit : "Deposit : RS.1 Lac", address : "Next Adyar National Park, 200 Feet Radial Road, Adyar", descriptionCom : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 134, imageUrl : "./images/Commercial Shop 11.jpg", imageUrl6 : "./images/Commercial Shop 15.jpg", imageUrl7 : "./images/Commercial Shop 7.jpg" , title : "Office space in T.Nagar, chennai for Rent", rent : "Rent : 22,000" , buildUp : "BuildUp : 520sq.ft", deposit : "Deposit : RS.2 Lac", address : "Next Saravana Stores, Usman Road, T.Nagar", descriptionCom : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."},
    {proid : 135, imageUrl : "./images/Commercial Shop 12.jpg", imageUrl6 : "./images/Commercial Shop 9.jpg", imageUrl7 : "./images/Commercial Shop 9.jpg" , title : "Office space in Madipakam, chennai for Rent", rent : "Rent : 45,000" , buildUp : "BuildUp : 789sq.ft", deposit : "Deposit : RS.4 Lac", address : "Next to Bus Stop, Near NGO colonu, Madipakam", descriptionCom : "This three bedroom for sale comes with an affordable price tag of just 1.08 Crores rupees with an additional perk of paying no brokerage. Situated on the 4th floor this home can comfortably serve your parking lot for a car and bike needs. This East facing home is over 1438 sqft. & is in a convenient location."}
];


